### ISSUE TITLE
Support list of blocks in addition to block ranges

### ISSUE THREAD

**Issue by ipatka** [paradigmxyz/cryo#11]
Allow blocks to be passed in as a list in addition to block ranges, perhaps as comma separated list

I'll make a pass at adding this today, just filing issue for visibility

**Comment by sslivkoff** [comment]
this should already work, as a space separated list

`cryo txs --blocks 16000000 16000001 16000002`

**Comment by ipatka** [comment]
huh not sure why i was getting parsing error, will check

**Comment by ipatka** [comment]
Found the issue, PR'd here https://github.com/paradigmxyz/cryo/pull/14
