### ISSUE TITLE
(Re-)activate `--event-signature` flag for `logs` dataset

### ISSUE THREAD

**Issue by cool-mestorf** [paradigmxyz/cryo#113]
**Is your feature request related to a problem? Please describe.**

Currently `--event-signature` cli flag exists but does not have any references in the codebase. Also there's no reference for log decoder object created and used. No log decoder object is passed to `table_schema` regardless of supplied cli param. ([code](https://github.com/paradigmxyz/cryo/blob/f0a0aa7d50a8efa474ba92d8d8894d1601fd8bff/crates/cli/src/parse/schemas.rs#L52))

example command with no difference of result - the latter is expected to have additional columns of `_from`, `_to` and `value`.

```bash
# USDT logs from random mainnet block
$ cryo logs --address 0xdAC17F958D2ee523a2206206994597C13D831ec7 -b 18556423:18556424 --csv
$ cryo logs --address 0xdAC17F958D2ee523a2206206994597C13D831ec7 -b 18556423:18556424 --csv --event-signature "event Transfer(address indexed _from, address indexed _to, uint256 _value)"
```

**Describe the solution you'd like**

Implement parsing log decoder from cli params.

**Comment by sslivkoff** [comment]
fixed in 0733f705e529bc51adda850d1f89b40cacf51eae
