### ISSUE TITLE
Contract filtering doesn't seem to work for logs

### ISSUE THREAD

**Issue by mwakaba2** [paradigmxyz/cryo#133]
**Version**
```bash
$ cryo --version
cryo 0.2.0-180-g6e9ec88
```

**Platform**
`Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 arm64`

**Description**

The `--contract` filter doesn't work for logs. 

I tried this code:

```bash
$  cryo logs \
    --label uniswap_v2_pools \
    --blocks latest --contract 0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f
```

<img width="1053" alt="Screenshot 2023-11-20 at 7 47 25 PM" src="https://github.com/paradigmxyz/cryo/assets/3497137/2704c882-7168-4f24-aea4-8641402779db">

I expected to see this happen: Only see logs for contract `0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f`

Instead, this happened: The parquet contains all logs for the latest block, so it seems like the contract filter isn't working.

**Comment by sslivkoff** [comment]
the argument is `--address`. #134 adds an alias so that `--contract` also works identically
