### ISSUE TITLE
Include an option for ABI decoding

### ISSUE THREAD

**Issue by mystmaker33** [paradigmxyz/cryo#18]
**Is your feature request related to a problem? Please describe.**
When getting logs include an option to decode them by providing a contract's ABI

**Describe the solution you'd like**
Since it is a CLI tool, it could take a parameter that points to a .json file that has the ABI and decodes before writing the file.

**Comment by 007vasy** [comment]
hey @sslivkoff, I wrote and maintain a log/trace decoder in python which can handle:

- nested component
- event/function hash collision
- function output decoding
- unnamed variables

can I help with the above feature?

**Comment by sslivkoff** [comment]
event coding is something cryo should have

related to #44
