### ISSUE TITLE
RPC url to invalid node shows 'parsing error' rather than RPC node error

### ISSUE THREAD

**Issue by ipatka** [paradigmxyz/cryo#23]
![Screen Shot 2023-08-07 at 1 06 48 PM](https://github.com/paradigmxyz/cryo/assets/4401444/00f79fba-345d-4dac-a37d-08335811b272)

Instead it should surface some error related to not connecting to RPC node

**Comment by ipatka** [comment]
Addressed here: https://github.com/paradigmxyz/cryo/pull/24

**Comment by sslivkoff** [comment]
fixed in ecf7407d0d0d0960a99f9ad6603009cde13602ac
