### ISSUE TITLE
collecting storage diffs for block 0 is broken

### ISSUE THREAD

**Issue by banteg** [paradigmxyz/cryo#31]
**Version**
cryo 0.2.0

**Platform**
linux x86_64

**Description**
I tried this code vs erigon client:
```
cryo storage_diffs -b 0
```

from erigon rpcdameon log:
```
method=trace_replayBlockTransactions
err="block 0000000000000000000000000000000000000000000000000000000000000000 not found"
```

block 0 should probably be skipped for storage diffs

**Comment by MRabenda** [comment]
I think would be not vise to skip them - as block can have storage changes

**Comment by banteg** [comment]
it only has genesis state. i filed a bug because the method crashes for block 0, so the cryo extraction crashes too.
