### ISSUE TITLE
perf: get block receipts instead of individual transaction receipts

### ISSUE THREAD

**Issue by banteg** [paradigmxyz/cryo#32]
https://github.com/paradigmxyz/cryo/blob/b2c221a6f4f2104e0a6022780cb44a59fed6a172/crates/freeze/src/datasets/blocks_and_transactions.rs#L128

we can use `eth_getBlockReceipts`, it's implemented in erigon and has recently been merged to execution spec.
https://github.com/ethereum/execution-apis/pull/438

**Comment by sslivkoff** [comment]
good call. implemented in 50b7fa9b3d5f6ddafd70ed577d153a2e3ef7326c
