### ISSUE TITLE
perf: dedup rpc requests when multiple datasets are requested

### ISSUE THREAD

**Issue by banteg** [paradigmxyz/cryo#33]
when cryo collects multiple datasets in the same run that use the same rpc, avoid making duplicate rpc requests.

for example, `cryo.freeze(['traces', 'contracts'])` uses `trace_block` and can extract the data from one response.

**Comment by seendsouza** [comment]
Hmm right now each datatype is a separate tokio task (freeze_multi_datatype_chunk), so maybe across each chunk we can have a shared memoization cache similar to https://github.com/graphql/dataloader#caching
