### ISSUE TITLE
Use MockProvider for better tests, using reth as an example

### ISSUE THREAD

**Issue by sslivkoff** [paradigmxyz/cryo#4]
**Is your feature request related to a problem? Please describe.**
Test coverage is currently poor and doesn't cover many failure modes.

**Describe the solution you'd like**
MockProvider should be used to create rich tests under a variety of response scenarios. Reth uses this approach extensively and can be used for inspiration.

**Comment by shawnharmsen** [comment]
I'd like to take a stab at this please

I think you mean here for the mock provider?
https://github.com/paradigmxyz/reth/blob/b823cc01778fd364a78279a2979f84ef79f954eb/crates/storage/provider/src/test_utils/mock.rs#L26

Will get a pr up soon!

**Comment by sslivkoff** [comment]
this has already begun in some of the tests, and more will come in the upcoming test overhaul
