### ISSUE TITLE
Request a means of filtering and ignoring reverted transactions

### ISSUE THREAD

**Issue by ashpoolin** [paradigmxyz/cryo#46]
**Is your feature request related to a problem? Please describe.**
The feature request addresses a product gap with Cryo... reverted transactions from parsed blocks (ex query: `cryo transactions --blocks 17M:latest --rpc http://localhost:8545 --csv)` appear identical to valid and successful transactions. Example tx hash: 0x2493dd272251ca0867cc014a8ec985b4954314c08ba596ad64661f5b3b13d831 

**Describe the solution you'd like**
stormnotstorm suggested this might be a solution: "ideally cryo should have some flag about how to handle this, either skipping those txs or adding a error column."

**Describe alternatives you've considered**
I've used naive methods of filtering bad txs: e.g. removing transfer values that exceed the market cap of a coin. This is not a correct solution, but what I have done for very crude removal of data that demonstrably corrupts my data set. A formal solution is greatly desired.

**Additional context**
See image of an invalid transaction and its resultant parsed output from a Cryo csv file (transaction_hash = 0x2493dd272251ca0867cc014a8ec985b4954314c08ba596ad64661f5b3b13d831).
![image](https://github.com/paradigmxyz/cryo/assets/103349226/ea4ea30a-5b31-4773-acb1-70b62f83824e)

**Comment by ashpoolin** [comment]
Anything able to be done on this? Having failed/reverted tx getting mixed into the data is rather undesirable. Going back and purging them afterward also an incredible chore.

**Comment by sslivkoff** [comment]
added in #89

you can use `--exclude-failed` to exclude

and if not, the `success` column will tell you whether each was successful
