### ISSUE TITLE
Add visual dashboard to track extracting status

### ISSUE THREAD

**Issue by sigridjineth** [paradigmxyz/cryo#48]
**Is your feature request related to a problem? Please describe.**
While extracting data using cryo, users lack a visual and intuitive means to monitor the progress and status of their extraction tasks. Without a real-time tracking mechanism, it becomes challenging to gauge extraction efficiency, potential issues, or bottlenecks that might be occurring during the extraction process.

**Describe the solution you'd like**
Introduce an interactive dashboard within cryo which can be accessed to public API/endpoint/k8s stats that provides real-time insights and metrics related to data extraction. Features of the dashboard could include:
* Progress bars indicating the completion status of ongoing extractions.
* Charts showcasing extraction speeds and rate-limiting metrics.
* Visual alerts or notifications for any errors or issues detected during extraction.
* An overview of data formats selected and the storage locations chosen (like S3, Azureblob, etc.).
* A historical log of past extraction tasks with timestamps, durations, and outcomes.

**Comment by banteg** [comment]
this can probably be built with https://dagster.io/

**Comment by sslivkoff** [comment]
I think supporting a gui should probably be handled by an external tool. This could be accomplished by a simple python tool that watches and analyzes the new files that appear in the cryo output dir. But implementing this in rust will add a lot of complexity and it's not clear that cryo is mature enough to endorse a particular gui stack when the low level architecture is still in flux

FWIW cryo already has
- progress bar
- file creation/modification times show rate of progress
- errors reporting is still very rough, would need to fix this deeper down the stack before creating a visual representation 
- high level management features will be handled by [`pdp`](https://github.com/paradigmxyz/paradigm-data-portal) which cryo is a partial reimplementation of. `pdp` will do the dataset management, `cryo` will do the extraction
- extraction reports are now saved in a .cryo folder

**Comment by sigridjineth** [comment]
nice thought. would create the additional layer (repository) to visualize this

**Comment by sslivkoff** [comment]
closing for now. can rehash in future when cryo becomes more stabilized
