### ISSUE TITLE
Incorrect expected chunk count

### ISSUE THREAD

**Issue by OwenKane** [paradigmxyz/cryo#69]
**Version**
latest

**Platform**
Darwin MacBook-Pro.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:19 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6020 arm64

**Description**
When executing a command to retrieve multiple datasets, cryo returns an incorrect expected chucks, thus an incorrect ETA.

For example, a command of 
```shell
cryo blocks txs traces --blocks 18183000:latest
```
latest = 18219277 @ execution time

Expects 37 chunks, but the actual is 74:
```shell
collection summary
──────────────────
- total duration: 1513.587 seconds
- t_start: 2023-09-26 12:12:50.922
- t_end:   2023-09-26 12:38:04.509
- chunks errored:   0 / 37
- chunks skipped:   0 / 37
- chunks collected: 74 / 37
- blocks collected: 72,556
- blocks per second: 47.9
- blocks per minute: 2,876.2
- blocks per hour:   172,571.2
- blocks per day:    4,141,709.6
```
Example of incorrect ETA:
![Screenshot 2023-09-26 at 12 32 17](https://github.com/paradigmxyz/cryo/assets/9117672/ea5ddf0b-2478-4f8f-92c9-d66cdc46c002)

**Comment by sslivkoff** [comment]
fixed in 322d665c42bec408342555396f9bcbfc9ab5629c
