### ISSUE TITLE
csv export error

### ISSUE THREAD

**Issue by prostate** [paradigmxyz/cryo#88]
**Version**
cryo 0.2.0-136-ga4747a4

**Platform**
64-bit (Windows)

**Description**
Unable to export as .csv 

command:
`cryo logs --contract 0xdb5889e35e379ef0498aae126fc2cce1fbd23216 --rpc <rpchere> --overwrite --blocks -5:latest --csv`

error: 
```
error summary
─────────────
(errors in 1 chunks)
- Collect failed: error writing file (1x)
```

unsure as to why this happens.

**Comment by sslivkoff** [comment]
fixed in #91
